#!/usr/bin/env python3
"""Slice the hash-pinned public 0.947 notebook into an importable post-processing module.

The module contains, verbatim, the notebook's environment configuration, path
constants, post-processing constants, post-processing/DeepCenter functions and
its validator metric functions.  Only the same three filesystem replacements as
model167/prepare_reproduction.py are applied (competition dir, working dir),
plus the IPython display import is dropped.  Nothing algorithmic changes.
"""

from __future__ import annotations

import hashlib
import json
from pathlib import Path

HERE = Path(__file__).resolve().parent
ROOT = HERE.parent
SOURCE = Path(r"C:\biohub_data\public\zhincez_ref\code.py")
NOTEBOOK = ROOT / "model167/public/zhincez/biohub-0-947-lb-runnable-with-public-datasets.ipynb"
NOTEBOOK_SHA256 = "38bca69a477e9090717c59c54358c2434e168042ac29734b9b12922aa7d0f186"
OUTPUT = HERE / "pp_module.py"
RECEIPT = HERE / "pp_module_receipt.json"

# 1-based inclusive line ranges of code.py (extracted code cells of the pinned notebook).
RANGES = [
    (3, 4),        # __future__ + os
    (32, 101),     # environment configuration block (BIOHUB_* env values)
    (134, 149),    # stdlib imports (+pandas, IPython display -> print)
    (152, 176),    # path constants
    (385, 473),    # post-process constants
    (1737, 1741),  # tracksdata/numpy/blosc2/scipy imports
    (1743, 3075),  # post-processing + DeepCenter + DEEPCENTER_VETO_DETECTOR
    (3195, 3201),  # TRAIN_DIR + validator constants
    (3349, 3604),  # validator matching / scoring functions
    (3606, 3623),  # PP_SWEEP_KEYS, pp_apply, pp_restore
]

REPLACEMENTS = {
    "COMP_DIR_CANDIDATES = [Path(f'/kaggle/input/competitions/{COMPETITION}'), Path(f'/kaggle/input/{COMPETITION}')]":
        "COMP_DIR_CANDIDATES = [Path(os.environ['BIOHUB_COMP_DIR'])] if os.environ.get('BIOHUB_COMP_DIR') else [Path(f'/kaggle/input/competitions/{COMPETITION}'), Path(f'/kaggle/input/{COMPETITION}')]",
    "WORKING_DIR = Path('/kaggle/working') if Path('/kaggle/working').exists() else Path('.')":
        "WORKING_DIR = Path(os.environ['BIOHUB_WORKING_DIR']) if os.environ.get('BIOHUB_WORKING_DIR') else (Path('/kaggle/working') if Path('/kaggle/working').exists() else Path('.'))",
    "from IPython.display import display": "display = print",
    "os.environ['BIOHUB_DEEPCENTER_CHECKPOINT'] = '/kaggle/input/datasets/pilkwang/biohub-deepcenter-unet3d-center-prior-v1/weights/full_frame_center/best.pt'":
        "os.environ.setdefault('BIOHUB_DEEPCENTER_CHECKPOINT', '/kaggle/input/datasets/pilkwang/biohub-deepcenter-unet3d-center-prior-v1/weights/full_frame_center/best.pt')",
}


def sha256(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def main() -> None:
    if sha256(NOTEBOOK) != NOTEBOOK_SHA256:
        raise RuntimeError("pinned notebook hash changed")
    lines = SOURCE.read_text(encoding="utf-8").splitlines(keepends=True)
    parts = ["# AUTO-GENERATED by model180/build_pp_module.py from the pinned public 0.947 notebook.\n",
             "# Do not edit; regenerate. Provenance in pp_module_receipt.json.\n"]
    for start, end in RANGES:
        parts.append(f"\n# ---- code.py lines {start}-{end} ----\n")
        parts.extend(lines[start - 1:end])
    text = "".join(parts)
    counts = {}
    for needle, replacement in REPLACEMENTS.items():
        counts[needle[:60]] = text.count(needle)
        text = text.replace(needle, replacement)
    if any(c != 1 for c in counts.values()):
        raise RuntimeError({"replacement_counts": counts})
    OUTPUT.write_text(text, encoding="utf-8")
    compile(text, str(OUTPUT), "exec")
    RECEIPT.write_text(json.dumps({
        "source_code_py_sha256": sha256(SOURCE),
        "notebook_sha256": NOTEBOOK_SHA256,
        "ranges": RANGES,
        "replacement_counts": counts,
        "output_sha256": sha256(OUTPUT),
        "algorithm_changes": 0,
    }, indent=2) + "\n", encoding="utf-8")
    print("wrote", OUTPUT, "lines", text.count("\n"))


if __name__ == "__main__":
    main()
